# site settings
title: Glenn Lanzer III
subtitle: by G3 Designs
email: myemail@mydomain.com
description: A responsive site template designed by G3 Designs
baseurl: "" # the subpath of your site, e.g. /blog
url: https://TexasBullet26.github.io # the base hostname & protocol for your site
author: Glenn Lanzer III
street_address: 99 My Own Lane
city: San Francisco
state: CA
zip_code: 99999
country: United States of America
phone: (999) 999 9999
timezone: America/Chicago

# opengraph
locale: en_US
logo: /assets/site/images/authors/glenn-lanzer.png

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# permalink: /:title/

paginate: 6
paginate_path: "/:title/blog-:num"

# categories
defaults:
  -
    scope:
      path: "" # "" -> all pages, "projects" -> (projects directory)
      type: "posts"
    values:
      layout: "post" # -> Use _layouts/post
      author: "Glenn Lanzer III"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  -
    scope:
      path: "twil"
      type: "posts"
      #paginate: "/alltwils/"
    values:
      layout: "post"
      author: "Glenn Lanzer III"
      category: "twil"
      permalink: "/:categories/:title/"
      # date: "%y%m%d%M"

  -
    scope:
      path: "alltwils"
      type: "posts"
    values:
      layout: "alltwils"
      category: "alltwils"
      permalink: "/:categories/:title/"

# contact form settings
form_url: https://formspree.io/lanzertrey@gmail.com # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url: https://facebook.com/trey.lanzer
github_url: https://github.com/TexasBullet26
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+lanzertrey
instagram_url: https://instagram.com/treylanzer
linkedin_url: https://www.linkedin.com/in/glenn-lanzer
pinterest_url: https://www.pinterest.com/glennlanzer/
slack_url:
twitter_url: https://twitter.com/LanzerTrey26

#plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-feed
#  - jemoji # Lets you include emoji
#  - github-pages

# External Services, leave blank to ignore or put true to use
service:
  google_analytics_key: "UA-99924733-3"
  disqus_key:
  muut: false
  google_adsense: false

comments: false

# build settings
markdown: kramdown

sass:
  style: compressed
