# site settings
title: Glenn Lanzer III
subtitle: by G3 Designs
email: lanzertrey@gmail.com
description: A responsive site template designed by G3 Designs
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Glenn Lanzer III
street_address: 7208 Sunburst Trail
city: Denton
state: TX
zip_code: 76210
country: United States of America
phone: (940) 300-8313

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/trey.lanzer
github_url: https://github.com/TexasBullet26
gitlab_url: 
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/treylanzer
linkedin_url: https://www.linkedin.com/in/glenn-lanzer
pinterest_url:
slack_url:
twitter_url: https://twitter.com/LanzerTrey26

# build settings
markdown: kramdown

sass:
  style: compressed
